Added Login and Register API
ofast-team/functions pull request #2
Opened 2023-11-08 07:25 UTC by tylerm390

Added login and register with email and password. The following was tested in postman:

Login with email:
- Logging in with an invalid email address (Response => "Invalid Email")
- Logging in with a valid email address that is not in the database (Response => "Invalid Credentials")
- Logging in with a valid email address but wrong password (Response => "Invalid Credentials")
- Logging in with a valid email address and valid password (Response => User ID)

Register with email:
- Registering with an invalid email address (Response => "Invalid Email")
- Registering with an email address already in use (Response => "Email in Use")
- Registering with a valid email address and valid password (Response => "User Create")

In addition, missing email and password fields in the input JSON are detected for both Login and Register with email.

Some formatting changes were also made to how I was importing certain functions.

2023-11-08 13:39 UTC, gblake31 approved these changes
I want to talk about naming choices for the response json, but I'm going to approve this now so we begin implementing the front-end part. The code isn't going to do any harm as is.

2023-11-08 14:06 UTC, cameroncuster requested changes
LGTM, but IMO we should add the docs

2023-11-08 14:06 UTC, cameroncuster commented on functions/src/index.ts
> +app.post('/loginWithEmail', (req: Request, res: Response) => {
I think we should use doxygen to document the API. It's super easy to use and is pretty standard (you'll notice they did this for the climbing project)

looks like this

```
/**
 * This is a comment.
 *
 * @param name The name of the parameter.
 * @return The return value of the function.
 */
int my_function(const char* name) {
  // Do something.
  return 0;
}
```

2023-11-09 16:19 UTC, cameroncuster requested changes
Code is looking good, but we should document with doxygen and also set up tests for each of the API functions (this will make our system more robust)

We also need to configre the action to run our test suite (I can set this up)

I'm happy to work with you to help knock some of this out since you've already done a lot.

2023-11-09 16:19 UTC, cameroncuster commented on functions/src/index.ts
> + */
let's use doxygen https://www.doxygen.nl/manual/starting.html

2023-11-09 16:39 UTC, cameroncuster approved these changes
Good point about not wanting this stuff to block Blake, approving.

2023-11-09 19:01 UTC, merged